# [package] section removed – this is a virtual workspace manifest

[workspace]
members = ["rust-core", "python-bindings"]

[workspace.package]
version  = "0.3.1"
edition  = "2024"
license  = "GPL-3.0"
